### ISSUE TITLE
Are there ever gonna be placeholders?

### ISSUE THREAD

**Issue by Zabsterv** [PrisonTeam/Prison#137]
Module: Ranks

I love the plugin, everything works except there no placeholders which is such a disappointment.
That leads me to a question, will the community ever make placeholders?
I'm trying to make a scoreboard that displays your rank and how much more money you need to get to the next rank with a bar below (or next) to it.

Truly would love a response,

Cheers!

**Comment by GABRYCA** [comment]
Woah sorry for the ultra late 1 month response, never saw this incoming before now.

Anyway, there's only a "DEV" build with it, untested at all, if you want to try it (i can't find the original one as outdated and automatically deleted, so i've found another one, the last build... maybe it's wrong because i haven't tried it at all)

Link: https://ci.appveyor.com/project/faizaand/prison/builds/25802944

**Comment by rbluer** [comment]
Release v3.2.0 includes placeholders.  Please download the Prison plugin v3.2.0 when it is available.
