### ISSUE TITLE
1.14.4 Support

### ISSUE THREAD

**Issue by Billanater** [PrisonTeam/Prison#142]
Hey,

This is just a general question on if this plugin is known to work on 1.14.4 or if there is a planned update to 1.14.4 of it

Thanks

**Comment by rbluer** [comment]
Currently this plugin does not work with 1.14.4.  I tried and a few others have too.  There have been some major libraries that have changed with 1.14.4 and as a result there are a number of class not found exceptions.

At this time I am unable to focus on trying to get it to work with 1.14.4 since I'm in the middle of a number of updates, bug fixes, and performance optimizations focused on the prison-mines module.  I'm not sure how long these items will take to complete.

I'm hopeful that the fixes needed for 1.14.4 could be rather "simple" in nature and not require any significant rewrites or fixes.  But what's making it difficult to judge the scope of the fixes is that it is unknown if there will be other failures once the initial issues are fixed.  Not sure if that makes sense? Basically I know of one major issue and once that is fixed, then a few other major issues may show themselves.  

So the short answer to your questions is that this plugin does not work yet, but I am wanting to get it working for 1.14.4, but I am uncertain as to when that will happen or how complex of a task that will be.  Time wise it could be a few weeks, to a few months, to possibly never? Sure hope never is not a reality.

Hope that helps to answer your question.  Sorry if I cannot provide more concrete specifics.

**Comment by Billanater** [comment]
> Hope that helps to answer your question. Sorry if I cannot provide more concrete specifics.

Thanks for the info

I definitely hope it gets updated soon cuz I cant find a good free alternative.

**Comment by rbluer** [comment]
You're welcome!  Feel free to "ping" me in a week or two to check in on how its going, and to "motivate" me to give it a try.  :)

**Comment by awaffle1** [comment]
I used to use regular Prison with 1.14.4 and it worked okay-ish.
It was fine, although some commands returned errors

**Comment by rbluer** [comment]
Well, there have been resource updates and it looks like some of those other resources have changed and no longer include key resources that this plugin relies upon.  We were forced to update to the newer versions of the resources since the older ones were actually removed from their repository.

We cannot control those other resource libraries, but in order to get this to work again with 1.14.4 we can pull in the now missing resources.  It will just take some time to figure out everything that is missing.  Hopefully once we get the 1.14.4 support enabled, there will be no errors anywhere.

**Comment by rbluer** [comment]
Release v3.2.0 works well in 1.14.4.  Please download the Prison plugin v3.2.0 when it is available.
