### ISSUE TITLE
 Ranks enable failed

### ISSUE THREAD

**Issue by brunosagaste** [PrisonTeam/Prison#146]
### Which module are you submitting this issue for?
Ranks

### Describe the issue you are experiencing.
When the server is loading, ranks fails to load.

### Describe the steps to reproduce the problem.
Prison 3.2 on Minecraft 1.15.1. Load the server using Vault and Ultimate_Economy. If I type /prison modules it returns "No economy pluggin", but Vault is hooking Ultimate_Economy fine (after the prison plugin starts).

### Anything else we need to know?

[19:37:03] [Server thread/INFO]: | Prison | Enable start... 
[19:37:03] [Server thread/INFO]: | Prison | Enabled Prison v3.2.0 in 74 milliseconds. [19:37:03] [Server thread/INFO]: | Prison | Mines enable start... 
[19:37:03] [Server thread/INFO]: | Prison | Loaded 1 mines 
[19:37:03] [Server thread/INFO]: | Prison | Mines enable succeeded, in 35 milliseconds. 
[19:37:03] [Server thread/INFO]: | Prison | Ranks enable start... 
[19:37:03] [Server thread/INFO]: | Prison | Ranks enable failed, in 1 milliseconds.

**Comment by rbluer** [comment]
Sorry, at this time the Prison plugin does not support 1.15.1. 

I just added support for 1.13.2 and 1.14.4.  But have not been able to consider 1.15.x yet.  I am not sure if there may be any core issues with 1.15.x that may break core functionality.

I could try to see if there are any major issues with supporting 1.15.x, but in all honesty I probably won't be able to get to it for a few weeks.  I'm needing to wrap up other changes before I try to add new resources and functionality.

For future reference when I test the 1.15.x environment, what version of Vault and Ultimate_Economy are you using?  Are there any other plugins that you think may be important that I should test for?

**Comment by brunosagaste** [comment]
I've tried 1.14.4 but i'm having the same issue.

Maybe I'm doing something wrong?
Vault is hooking Ultimate_Economy after Prison starts. I've tried Chestshop and Vault is loading after Prison too. Maybe is a dependency problem?

I'm using Vault 1.7.2 and Ultimate_Economy 1.2.3b. Also World Edit, World Guard, an economy plugin and Bssentials are important plugins for the server. 

There is any economy plugin or vault version that you recommend or tested?
I've tried SaneEconomy without vault as the documentation suggest but is not working either. 
/prison modules keeps returning that there is no economy plugin.

The only workaround I found is to use another rank plugin, instead of the prison built in.

**Comment by brunosagaste** [comment]
![vault](https://user-images.githubusercontent.com/26704229/71525382-23e84080-28b0-11ea-8e8b-a51e85903fc2.PNG)

**Comment by rbluer** [comment]
I'm working on adding new functionality to the mine resets to improve performance drastically.  So that way if you have 100+ mines it will no longer lag the server.  I'm also adding better support for multi-language support so there are less hard-coded English text in the game to improve the game play for others.

Then I will be adding more support for other economy, placeholders, and other plugins.  I'll be trying to get minecraft 1.15.x working too.  

So that's the high-level plans for now... I'm mentioning what's currently in development since it looks like Ultimate_Economy is not supported yet; I can add that when I work on expanding the plugin support shortly.

The current supported plugins are the following, but I'm not sure about the actual supported versions of each plugin, which may be more dependent upon the minecraft version your running.
* Essentials
* SaneEconomy
* Vault - Economy
* LuckPerms pre v5
* LuckPerms v5 if using LuckPerm's Legacy API jar (native v5 support will be added in near future)
* Vault - Perms
* MVDWPlaceHolderAPI
* PlaceholderAPI

Hope that helps.  If not, please let me know.

**Comment by brunosagaste** [comment]
Thank you for you help and for the list. I was able to make it work with Essentials on both 1.14.4 and 1.15.1. The ranks works fine. I didn't know that Ultimate_Economy was not supported. When I searched for a supported plugins list I couldn't find any. Your web page https://faizaand.me/prison where there is more information about using this plugin seems to be down. 

The core plugins of my server, wich are PermissionsEx, Essentials, ChestShop, World Edit, World Guard, and AuthMe are working fine with Prison.

Thank you again. Maybe the best thing to do is put more detailed documentation online.
