### ISSUE TITLE
Prison 3.2 Plugin not working at all

### ISSUE THREAD

**Issue by Hendrick020301** [PrisonTeam/Prison#152]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?

The plugin itself

### Describe the issue you are experiencing.
I've downloaded the version 3.2 but keep getting the alert that a newer version is available, version 3.2.
And when i type in /prison modules, no modules are being shown.
im running spigot 1.14.4

### Describe the steps to reproduce the problem.
Just downloaded the plugin and dropped it into my plugins folder

### Anything else we need to know?
Running the latest version of spigot 1.14.4 via ApexHosting.

**Comment by Hendrick020301** [comment]
Little Addition, none of the /mines commands work. Ive thought that maybe im missing some  dependency plugins but there wasnt any information about that so i assume you dont need any.

**Comment by GABRYCA** [comment]
Hi,
Which permission plugin are you using?
LuckPerms 5.0 gives issues, so we suggest to try one of ours beta.
Please join the discord channel if you want more direct help.

Let me know if you've luckperms v5.0 or up, it could be problem.

Otherwise, to make ranks works, you need to install an economy plugin, such as Vault and EssentialsX together.

**Comment by rbluer** [comment]
The only time we see this issue, is if someone is trying to use LuckPerms v5.0.x with Prison v5.2.0 or earlier.  LuckPerms v5.0.x is not supported with Prison v5.2.0 and earlier.  The problems that LuckPerms v5.0.x created has been fixed in the pre-release version of prison.

The tool that prison uses to monitor if new versions are available is called SpiGet.  It does not always work well, since their handling of semantic versions is non-standard.  This issue has been fixed in the pre-release of prison by rewriting the interface to properly handle semantic versions.

The issues with /prison modules not working is related to LuckPerms v5.0.x; LuckPerms v5.0.x causes hard fails internally.  Prison does not have any hard dependencies so it should play well with others.

Since you are using the prison version as supplied by your hosting service, then I suggest that you downgrade to LuckPerms v4.4.1 and all should work fine.

The newest release of Prison that resolves all these issues, plus adds a ton of new features, is due to be released within the next few weeks.

Please let us know what version of LuckPerms that you are using, since we suspect it is v5.0.x.  Also please let us know if you get it working too.  If you need more support, consider visiting our discord page for faster responses.  Thanks and good luck!

**Comment by GABRYCA** [comment]
"The only time we see this issue, is if someone is trying to use LuckPerms v5.0.x with Prison v5.2.0 or earlier" 3.2*

**Comment by Hendrick020301** [comment]
Have been looking all over  the internet for luckperms v4.4.1 but couldnt find it anywhere.
If this issue is known cant  it  be fixed?

**Comment by GABRYCA** [comment]
we fixed it in a beta, we uploaded it in the dircord channel #support-bleeding

**Comment by rbluer** [comment]
LuckPerms v4.4.1 can be found on the spigot page:

https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/history

Yes their mistake was fixed in prison. The pre-release version works fine with both v5.0.x and older versions of luckperms.

**Comment by rbluer** [comment]
I'm assuming you were able to resolve your issues, so I'm closing this.

If you still have questions or issues, please visit our discord better assistance. https://discord.gg/396ed5F
