### ISSUE TITLE
Problem: /mine doesn't work

### ISSUE THREAD

**Issue by this7username7is7not7available** [PrisonTeam/Prison#160]
[As a side note could I get a link to the discord? The other one is invalid]
Ok so I'm kind of a newbie to server hosting, but I got a Bukkit server running and I was adding a lot of plugins.
### Which module are you submitting this issue for?

Mines, but I'm pretty sure there wasn't ranks either

### Describe the issue you are experiencing.
When I installed the plugin, I started up the server. The /prison command was working, but /mines simply didn't exist. Also, there's no config.json.

### Describe the steps to reproduce the problem.
Use Prison 3.2 and download it to the plugins section of your server. Afterwards, start your server and wait for the server to be up. Join and try /mines.

Thank you!

**Comment by GABRYCA** [comment]
Hi, please try /prison modules and check if they're both red or error.
Here's a link for the discord server: https://discord.gg/2GvbVAM

**Comment by this7username7is7not7available** [comment]
Hi, I uninstalled the plugin but when I did try it, it showed the prison modules screen but there were no modules.

**Comment by rbluer** [comment]
Odds are very high that you are using the unsupported LuckPerms v5.0.x with Prison v3.2.0.  Only LuckPerms v4.4.1 is supported with that version of Prison since LuckPerms v5.0.x causes the problem that you are describing.

If you want to use the pre-release version of Prison, v3.2.1 which supports any version of LuckPerms, then please visit the discord server at the URL that GABRYCA provided above and see the channel #support-bleeding.

**Comment by this7username7is7not7available** [comment]
Thanks! It worked

**Comment by rbluer** [comment]
Great to hear! 
If you have any other questions or issues, feel free to reach out through the discord server.
