### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by srnyx** [PrisonTeam/Prison#162]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?

All

### Describe the issue you are experiencing.
Include details such as what you did, what happened, and what you think should have happened.
The plugin just isn't working, when I try and use a command it says an internal error has occurred, and there are no files in the modules folder.
### Describe the steps to reproduce the problem.
Here, you should tell us what we need to know in order to cause the same problem on our machines, so that we may debug it. Please include your Spigot, Prison, and dependency versions. This section is only needed if you are making a bug report.
1. Install plugin
2. Start server
### Anything else we need to know?

I'm not 100% certain but it **maybe** something in the config.yml file

**Comment by srnyx** [comment]
```
28.04 09:38:22 [Server] INFO [Prison] Enabling Prison v3.2.0*
28.04 09:38:22 [Server] INFO [Prison] Using version adapter tech.mcprison.prison.spigot.compat.Spigot19
28.04 09:38:22 [Server] INFO _____      _                 
28.04 09:38:22 [Server] INFO |  __ \    (_)                
28.04 09:38:22 [Server] INFO | |__) | __ _ ___  ___  _ __  
28.04 09:38:22 [Server] INFO |  ___/ '__| / __|/ _ \| '_ \
28.04 09:38:22 [Server] INFO | |   | |  | \__ \ (_) | | | |
28.04 09:38:22 [Server] INFO |_|   |_|  |_|___/\___/|_| |_|
28.04 09:38:22 [Server] INFO Loading version 3.2.0 on platform SpigotPlatform...
28.04 09:38:22 [Server] INFO | Prison | Enable start...
28.04 09:38:22 [Server] INFO | Prison | Enabled Prison v3.2.0 in 125 milliseconds.
28.04 09:38:22 [Server] ERROR Error occurred while enabling Prison v3.2.0 (Is it up to date?)
```

**Comment by rbluer** [comment]
Your report is totally useless.  You have given zero information on what version of spigot that you're using or the versions of any otherplugin.  You copied and pasted just the "error" without any other information that was provided in the console that could have helped solve the problem.

But, that said, your problem is that you are using an unsupported version of LuckPerms with Prison v3.2.0.  The problem is not prison, but luckperms.  This problem has been addressed so many times before too.

1. Downgrade to LuckPerms v4.4.1 with prison v.3.2.0.

2. Or use the pre-release version of prison since it fixes the problems that LuckPerms created and the pre-release version of prison works with any version of luckperms.

**Comment by srnyx** [comment]
PaperSpigot 1.14.4
And sorry, it never said you needed the version or even the console error.
