### ISSUE TITLE
Add a guard for a mine so a certain rank could access it

### ISSUE THREAD

**Issue by Aksm1234** [PrisonTeam/Prison#170]

**Comment by rbluer** [comment]
Overall your suggestion is great, but it is out of scope of what Prison is trying to focus on.

Protecting mines in this way is not the function of Prison and this will not be added in the future.  It is out of scope of the plugin due to the complexities involved, and that other plugins do a very good job with this behavior as they currently exist.  The other plugins do a great job and are well debugged and are also very stable.  Also they integrate well with many permission plugins.

Please see the "Configuring and Using WorldGuard with LuckPerms to Protect Mines" document near the bottom on the table of contents, which is found here:
https://github.com/PrisonTeam/Prison/blob/bleeding/docs/prison_docs_000_toc.md

That document explains in detail how to protect mines and the areas around the mines.

If you have other questions, please ask on the discord server for better support.
