### ISSUE TITLE
Prison Mines

### ISSUE THREAD

**Issue by Guns29** [PrisonTeam/Prison#171]
Mines

Well after every /restart /stop on the server mines delete so other's have have suggest that i try it in the air and nope mines just deletes it self 
please if it is possible to add a /mines save config to make sure it does not delete it self again would be helpful 

Server ver. 1.14 / 1.15.2
minecraft ver. 1.15.2

**Comment by rbluer** [comment]
Prison mines never just disappear.  There is a fail-safe mechanism to help ensure they are not lost.  Take a look under plugins/Prison/data_storage/mines/mines to confirm.  All changes you make to a mine is saved right away to the server's file system.  Even if you "delete" a mine, it will still be saved on the server file system.

Oh, yeah, but this is assuming you are using Prison v3.2.0 or newer.  Older versions of Prison, such as v3.1.1 would only save the configs for everything on "clean shutdowns".  Otherwise you would lose everything like what you are describing.  Older versions of prison is no longer supported.

It is strongly suggested that you upgrade to the latest version of prison.  If you upgrade to v3.2.0 keep in mind that version of prison only supports LuckPerms v4.4.1 and older.  If you upgrade to the pre-release version of prison (recommended), which is at v3.2.1-alpha.13, it works with all versions of LuckPerms including v5.0.x.

You can find Prison v3.2.0 on spigotmc.org.  The pre-release version of prison can be found on the prison discord server.

Probably what your real problem is, is

**Comment by Crystalz-PrisonSupport** [comment]
This ticket has been closed. If you have any other issues please open a new ticket.
