### ISSUE TITLE
Teleporting to mines

### ISSUE THREAD

**Issue by LokiTheGod123** [PrisonTeam/Prison#174]
### Which module are you submitting this issue for?

MINES AND RANKS, SPIGOT

### Describe the issue you are experiencing.
Include details such as what you did, what happened, and what you think should have happened.

I’ve built mines on separate islands. I made mines named a-z and ranks named a-z. I ranked up to first rank (a) and i want to mine in mine a. As mines are on separate islands I need to teleport to the mine but I can’t because I dont have the permission to use /mines tp. I don’t want to give myself /mines tp permission because I want only to tp to first mine as I have to first rank. Same if someone had rank d, he should be able to teleport to mine d and below ( a,b,c)

### Describe the steps to reproduce the problem.
Here, you should tell us what we need to know in order to cause the same problem on our machines, so that we may debug it. Please include your Spigot, Prison, and dependency versions. This section is only needed if you are making a bug report.

### Anything else we need to know?
Is there a way to do this? If not could you please add this in next update

**Comment by GABRYCA** [comment]
Hi,
There're per Mines tp permissions, try to execute a command like /mines tp <minename> help, it'll show you the exact permission.

**Comment by rbluer** [comment]
If you have additional questions, please visit our discord server: [Prison Discord](https://discord.gg/DCJ3j6r).

The help command that Gabryca mentioned, can be used after any prison command; just use the word help as if it is the first parameter.  The help command shows all permissions that are associated with the commands.

For the command `/mines tp <mineName>` it would require the permission of `mines.tp.<mineName>` to allow the players to use that command.

So if a player ranks up to B, they would be able to use the command `/mines tp b` to get there.  That's a lot for a player to type.  But what you could also do is to use the plugin MyCommand and map all of those TP commands to the single letter... for example the MyCommand config file would look like this:

  
```
##WARPS

a_warp:
  command: /a
  type: ALIAS
  alias: /mines tp a
  permission-required: false
  
b_warp:
  command: /b
  type: ALIAS
  alias: /mines tp b
  permission-required: false
``` 

Realize that permission-required is not needed because the prison command will perform the checks.  

So with the command remappings then the players would only have to use the following command:
```
/b
```

Oh yeah, I should mention that granting the permission to the players for the mine TP does require the pre-release version of prison.  You can access that version from our discord server (see link above) in the `#alpha-versions` channel.

Hope that helps... stop by our discord server if you have any other questions.
  Blue

**Comment by LokiTheGod123** [comment]
Sorry for bothering you again.
So this permission will be added automaticaly to   each player who ranks up (I rank up to rank b and I can teleport to mine a and b)? After adding the pre-release version to plugins folder do I need to remove to prison plugin downloaded from spigot mc? Does it mean that I will need to set up mines and ranks again?

**Comment by GABRYCA** [comment]
No, you must add a rankupcommand executing the command of your permissions manager which adds that permission, also replacing "player" with a placeholder like {player} if needed

**Comment by LokiTheGod123** [comment]
How can I add a rankupcommand? 
It’s so complicated😂

**Comment by rbluer** [comment]
Can you use discord? It will be far easier to help you there.  See my message above with the link.

Please review our documentation, that could help too.  

This document explains how to add rank up commands. It's pretty easy actually. At the top of that document is a link to get you back to the table of contents.
https://github.com/PrisonTeam/Prison/blob/bleeding/docs/prison_docs_626_configuring_worldguard_regions.md

This one provides a quick run down on how to setup mines with a few examples.
https://github.com/PrisonTeam/Prison/blob/bleeding/docs/prison_docs_101_setting_up_mines.md

Hope to see you on discord... ;)

**Comment by GABRYCA** [comment]
We have some guidebooks explaining that, you can find them here: https://github.com/PrisonTeam/Prison/blob/bleeding/docs/prison_docs_000_toc.md

with /prison you'll get a list of commands, it's everything self explanatory, /ranks will show all the ranks commands and /mines all the mines commands.
Search for /ranks and rankupcommands, a rankupcommand it's a command which will be executed when you rankup to the rank with that command, for example: If you're at A and rankup to B and the B rank have a rankupcommand like "w {player} Hi, you're at B", the guy who did rankup will get that command executed

**Comment by LokiTheGod123** [comment]
My discord username is AAABBBCCC
😂😂😂
If I have any questions I will ask them on discord.
