### ISSUE TITLE
restart config issue

### ISSUE THREAD

**Issue by VovelPunch** [PrisonTeam/Prison#226]
Configs are messed up upon restart for example I set up mines ranks a to z then restart server like hour later all configs are then messed up and /gui and / mines dont work. Then I have to delete config and redo everything...

**Comment by rbluer** [comment]
It sounds like you are manually editing the config files?

We strongly advise against making any manual config changes to the mines, ranks, or ladder config files, since it's is rather easy to mess them up and corrupt your server.

If you did make manual changes to them, then you're on your own for the most part, since we strongly advise not to do that.  But you may be able to track down your mistakes by using a an online tool like jsonlint.com to validate and fix the json data structure.

If you need help, visit our discord server for better assistance.

**Comment by VovelPunch** [comment]
no I used the auto configure and configured all the mines with via the gui. at 12:00PM server restarts and then i noticed all my efforts were deleted. Well not deleted just messed up. 
Maybe Mohist causes issues?

**Comment by rbluer** [comment]
Please visit our discord server and ping me (RoyalBlueRanger) and/or start a new thread.

I have put a lot of careful consideration in to this plugin so that none of the config settings, or the data, can be lost.  

Prior to taking over this project, with Prison versions prior to v3.2.0, it was possible that all configs could be lost if the server should shut down improperly.  But if you're running one of the latest versions, then data loss should be near to impossible.

We do not support Mohist, but since it is based upon Spigot, it should work fine.  If I can get setup information from you, I can build a test server to review what's going on. 

Let's talk in more detail on the discord server.... thanks, and sorry for any issues you are having.
 - Blue

**Comment by rbluer** [comment]
closing this item since it has been addressed in the discord server...
