### ISSUE TITLE
Don't reset cursor position when changing page

### ISSUE THREAD

**Issue by Josh-65** [PrisonTeam/Prison#244]
### Which module are you submitting this issue for?
Mines

### Describe the issue you are experiencing.
When changing the page of add block in the mines setup the cursor get set to 4th slot of the bottom row

### Describe the steps to reproduce the problem.
1. Open /gui admin mines
2. Open mine blocks config
3. Open add block page
4. Click the next or pervious buttons
5. See cursor position moved

**Comment by rbluer** [comment]
Thanks Josh for the suggestion.

I'm not sure if we really can control "cursor" positions when closing an inventory item, and opening another.

I'll have to test this to better understand what you mean by "cursor" since I have a feeling you may referring to what you're holding in the hot-bar and not the actual text cursor.

But please feel free to open a thread on our discord server so we can address all these items at the same time.

Thanks for the suggestion.

**Comment by rbluer** [comment]
Ok, I just reviewed what you were talking about, and I understand what you were say.

I agree. It's not that great and it's actually a pain to use because there are so many blocks, and once you make your selection, it dumps you out of the admin menus all together.  So you have to trudge through many screens over and over again.

First, let me say that I do understand this issue and I totally agree with you on many reasons why it's not that easy to use.

But, I'm going to close this issue and mark it as "will not fix" because the admin GUI functions are not what I would consider up to date.  They are difficult to maintain, and they are lacking many, many features that are within the general commands within prison.  The GUIs will never be able to replace the main commands one-for-one.  Therefore they are not even updated when new commands are added, or when features change within commands. 

Some day the admin GUIs may be eliminated (some already have been).

But another primary reason why no effort is put in to updating the admin GUIs is because I'm planning on rewriting the GUI engine within prison to allow the creation of dynamic menus and commands based 100% on configuration files.  Right now, every single aspect of the admin GUIs is controlled by many lines of Java code, so it's difficult to make even the slightest change.  In the future, it should be far easier to generate menus since it will require zero lines of programming changes.  

At that time, when the new GUI engine is in place, then it may be easier to update the admin pages to better reflect all of the actual commands and their options.  But at this time, there are far too many other important features, enhancements, and bug fixes that need to be addressed, before silly admin GUIs are enhanced.  I'm calling it silly because only the admins will see them, and only the admins will curse them. LOL  So why put weeks of effort in to changing something that will have zero impact on the players, and minimal on admins.

I strongly suggest that the admin GUIs should not be used, but instead please use the regular commands since they offer more features that are not available through the GUIs.  Plus there is more online help available through the regular commands.

I'm closing this issue as "will not fix" for the above stated reasons, but I do appreciate you taking the time to make the suggestions.

**Comment by Josh-65** [comment]
Alright thank for the explanation
