### ISSUE TITLE
Show ore blocks on first page

### ISSUE THREAD

**Issue by Josh-65** [PrisonTeam/Prison#245]
### Which module are you submitting this issue for?
Mines

### Describe the issue you are experiencing.
When adding blocks for a mine it most likely is going to be ores. Having to go through many page slowly per block added it take a long time to do.

**Comment by rbluer** [comment]
Thanks for the suggestion Josh.

Actually prison has no idea what type of blocks are what.  We use a third party library for referencing blocks to help ensure that we are 100% compatible with spigot 1.8.x through 1.20.x.  That library does not track block types.

You can enter multiple search strings within the block search tool and you can enter "ore".  That would only show the ores that apply to your version of bukkit that is running on your server.  If you select an ore and want to add another, then just press up arrow on the keyboard then enter.  You don't have to retype the whole command.  
NOTE: you can only enter one search term at a time, it does not support multiple keywords.

`/mines block search ore`

If you are looking for items you can use the following which includes both blocks and items.  This is useful when setting up the correct item names that you may want to use with SELLALL.
`/mines block searchAll`

I'm closing this since it's not really something we can "fix" since it's not really broken.  But it's a great idea.

If you want to discuss this farther, please open a thread on our discord server.

**Comment by rbluer** [comment]
Sorry, I thought I already closed this issue yesterday.  I must have clicked the wrong button.
