### ISSUE TITLE
Include mine configs in the reload command

### ISSUE THREAD

**Issue by Josh-65** [PrisonTeam/Prison#246]
### Which module are you submitting this issue for?
Core

### Describe the issue you are experiencing.
There's many time I prefer going through the file of a mine rather then the in game commands and UI. Issue is that I have to stop the server > Ctrl + Z to get my changes back on every mine file > save the files > start the server again.

**Comment by rbluer** [comment]
Josh, I'm sorry you're having issues with restarting the server so many times.

But we strongly discourage anyone from manually editing the mine or rank configuration files since the validation to ensure they have the correct settings are done though the admin commands.  No validation is performed when loading from these configuration files.  Therefore if you mess up the json format, or you put in an invalid setting, it could cause problems for prison, or even corrupt your world/game.  Example is if you mess up on the coordinates of a mine and accidentally have it wipe out any of your builds.

If anyone makes manual changes to these config files (mines, ranks, ladders) then they assume any risk if they make any mistakes while editing, or causes any corruption or losses to their builds or worlds.  We would not be able to help you undo any problems that may occur. 

I'm closing this issue because we will never support manual edits on mines in the near future.  Eventually we will in release v4.0, but its not on our radar at this time.
