### ISSUE TITLE
Update reload command to include translation files

### ISSUE THREAD

**Issue by Josh-65** [PrisonTeam/Prison#247]
### Which module are you submitting this issue for?
Core

### Describe the issue you are experiencing.
Doing `/prison reload` doesn't work for translation files. Requiring a server restart

**Comment by rbluer** [comment]
Your using the wrong command. It's '/prison reload locale'
I'll close this when I get home.
You can always just use discord to ask simple questions since you already
have a few threads open (any thread is fine).

**Comment by Josh-65** [comment]
Didn't seem like it existed that why I put it here.

**Comment by rbluer** [comment]
The term "Locale" is based upon the jargon that Java uses when a language is selected for use, and it influences many internal behaviors in java, such as formatting numerics, and altering the multi-language translations used for errors and other general notifications.  Prison utilizes the specified locale to control the internal multi-language engine.  So hence is why we use that as a descriptor for the command to reload it.

I stated the incorrect command before.  The correct command is plural:
`/prison reload locale`

That command does not have aliases setup for it, but if you wish, you can define your own alias within the config.yml setting file under `prisonCommandHandleraliases.prison.reload.locale` would be the correct yaml path to use.

Prison has a lot of features, many may not be even documented, so feel free to ask on our discord server if you're not finding something that you need.

Thanks for closing this ticket.  I'm marking it as invalid since it really isn't an issue and the feature already exist.  But thanks for reaching out. ;)
