### ISSUE TITLE
[Prison Bug]When there is a special lore item in the backpack, the recall will be executed, but the item will not disappear

### ISSUE THREAD

**Issue by Coquettishpig** [PrisonTeam/Prison#260]
![image](https://github.com/PrisonTeam/Prison/assets/107100449/9692522a-5dca-4c09-9f48-a3546f72660b)

**Comment by Coquettishpig** [comment]
Items with lore can only be sold if they're in hand, I'd like to support the idea of only being able to sell normal items with no lore

**Comment by rbluer** [comment]
We've indicated in the documentation that you should not use prison backpacks because they have some serious issues and that they will be replaced in the future.  I'm not sure when.

The items with lore, are their names identical to the vanilla minecraft items?  If they are not the same, then they should not be impacted by the prison sellall.  I've been wanting to expand the functionality of sellall for a while but have not been able to get time to do that; maybe now is a great time to get started. 

If you would like to, I'd suggest you visit out discord server and open a new thread there.  I can better work with you to get what you need working.  Ping me when you do: RoyalBlueRanger.

**Comment by rbluer** [comment]
I'm closing this issue because the sellall has been updated to only sell items without lore. 

Prison also has the ability now within sellall to indicate that an item with lore can be sold by setting the lore filters too.

Please see the latest release.
