### ISSUE TITLE
Sponge Implementation

### ISSUE THREAD

**Issue by faizaand** [PrisonTeam/Prison#5]
Now that Sponge API 5 is out, it's time that the Prison-Sponge implementation should be written. The Sponge implementation should ensure full compatibility with the core, in the same way that the Spigot implementation is.
- [ ] Commands
- [ ] Economy
- [ ] GUIs
- [ ] World Selection
- [ ] Storage

**Comment by DMP9-MC** [comment]
Assumed it was done, when it is only partially done

**Comment by Camouflage100** [comment]
Good job... 😂😂

**Comment by DMP9-MC** [comment]
Shhh 😶

**Comment by DMP9-MC** [comment]
I'm questioning if this will be ready for the Initial Release...

**Comment by Camouflage100** [comment]
Will start working on this within the next couple of days

**Comment by faizaand** [comment]
Abandoning vision of multi-platform support.

**Comment by rbluer** [comment]
The sponge module has been disabled with no immediate plans to work on it; there are too many missing components.  To retain the module would provide false advertising that prison may work with sponge.

Closing this issue due to the fact that the evolution of prison has resulted in too many core functions within the Sponge module either being empty with no code, or it returns nulls, there are no comparable .  
As it stands with v3.2.1 the sponge module is highly nonfunctional and would require extensive amount of work just to get minimal functionality out of it.  

The references within gradle to the sponge module have been commented out so the module will no longer build or produce exceptions as new features are added to the prison core.  No sponge code has been removed, so it can be resurrected in the future if someone so desires, but at this time efforts are focusing on improving prison.
